site_name: Github star count
site_url: https://adnene-guessoum.github.io/Github_cli/

theme:
  name: material

nav:
  - Home: index.md
  - Quick-start: quick_start.md
  - FAQ: faq.md
  - Source Code: source_code.md
  - Coverage Report: coverage.md

plugins:
  - search
  - mkdocstrings
  - coverage


